### ISSUE TITLE
Support expressions after a `;` chain

### ISSUE THREAD

**Issue by robotlolita** [siren-lang/siren#47]
Right now it's only possible to use a single message after the chain operator. It would be nice if the syntax supported whole expressions instead. E.g.:

```ruby
Mirror reflect: x; meta name
# => (Mirror reflect: x) meta name

xs sorted-by: f; first! + 1
# => (xs sorted-by: f) first! + 1
```

**Comment by vendethiel** [comment]
Does this also work? `xs first-by: criteria; + 1`? (I have no idea how this'd work, but I guess allowing a partial chain as the lhs of a binary op is ..)

**Comment by robotlolita** [comment]
It does. You can even write things like: `1; + 2 predecessor + 3 successor`, which would be equivalent to `((1) + (2 predecessor)) + (3 successor)`

**Comment by vendethiel** [comment]
ooh, that looks really cool :+1:
