### ISSUE TITLE
adt-simple in dependencies and devDependencies.

### ISSUE THREAD

**Issue by wavebeem** [siren-lang/siren#90]
It sounds like you accidentally saved `adt-simple` to both types of dependencies. Not sure which one it needs to be.

```
npm WARN package.json Dependency 'adt-simple' exists in both dependencies and devDependencies, using 'adt-simple@^0.1.3' from dependencies
```

**Comment by vendethiel** [comment]
should only be in dev, since it's used to build the compiler, I guess?

**Comment by robotlolita** [comment]
Ah, it should be only in `dependencies`. It's in both because adt-simple provides both a set of macros (which are used at compile time), and a set of derivations for the adts (which are used at runtime).
